name = "kentekencheck-net"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
main = "./dist/_worker.js"

[assets]
directory = "./dist"

routes = [
  { pattern = "kentekencheck.net/*", custom_domain = true },
  { pattern = "www.kentekencheck.net/*", custom_domain = true },
]
